<a href="https://colab.research.google.com/github/wisdomscode/AI-Lab-Deep-Learning-PyTorch/blob/main/AI_Lab_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Working with Tensor

In [1]:
import os
import sys

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import PIL
import torch
import torchvision
from PIL import Image
from torchvision import transforms

In [2]:
print("Platform:", sys.platform)
print("Python version:", sys.version)
print("---")
print("matplotlib version:", matplotlib.__version__)
print("pandas version:", pd.__version__)
print("PIL version:", PIL.__version__)
print("torch version:", torch.__version__)
print("torchvision version:", torchvision.__version__)

Platform: linux
Python version: 3.11.11 (main, Dec  4 2024, 08:55:07) [GCC 11.4.0]
---
matplotlib version: 3.10.0
pandas version: 2.2.2
PIL version: 11.1.0
torch version: 2.5.1+cu124
torchvision version: 0.20.1+cu124


In [3]:
# Declare my_tensor
my_values = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
my_tensor = torch.Tensor(my_values)

print("my_tensor class:", type(my_tensor))
print(my_tensor)

my_tensor class: <class 'torch.Tensor'>
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


Tensor Attributes

Task 1.1.2

In [ ]:
#Tensor attributes eg (dimenstions 'shape' and data type 'dtype')
print("my_tensor shape:", my_tensor.shape)

print("my_tensor dtype:", my_tensor.dtype)

my_tensor shape: torch.Size([4, 3])
my_tensor dtype: torch.float32


Task 1.1.3

In [ ]:
# Tensor Device - Tell us the hardware tensor is installed
print("my_tensor device:", my_tensor.device)

my_tensor device: cpu


In [4]:
#Some computers come with GPUs, which allow for bigger and faster model building.
#In PyTorch, the cuda package is used to access GPUs on Linux and Windows machines;
#mps is used on Macs.

# Check if GPUs available via `cuda`
cuda_gpus_available = torch.cuda.is_available()

print("cuda GPUs available:", cuda_gpus_available)


cuda GPUs available: True


Task 1.1.4 Change Device

In [5]:
# Change the device from cpu to gpu 'cuda'
my_tensor = my_tensor.to("cuda")

print("my_tensor device:", my_tensor.device)

my_tensor device: cuda:0


Tensor Slicing

Task 1.1.5

In [6]:
#Tensor Slicing - using [] and indexing to select a subset of the values in a tensor
#Slice my_tensor, assigning its top two rows to left_tensor and its bottom two rows to right_tensor.
left_tensor = my_tensor[:2 :]
right_tensor = my_tensor[2: :]

print("left_tensor class:", type(left_tensor))
print("left_tensor shape:", left_tensor.shape)
print("left_tensor data type:", left_tensor.dtype)
print("left_tensor device:", left_tensor.device)
print(left_tensor)
print()
print("right_tensor class:", type(right_tensor))
print("right_tensor shape:", right_tensor.shape)
print("right_tensor data type:", right_tensor.dtype)
print("right_tensor device:", right_tensor.device)
print(right_tensor)

left_tensor class: <class 'torch.Tensor'>
left_tensor shape: torch.Size([2, 3])
left_tensor data type: torch.float32
left_tensor device: cuda:0
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

right_tensor class: <class 'torch.Tensor'>
right_tensor shape: torch.Size([2, 3])
right_tensor data type: torch.float32
right_tensor device: cuda:0
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]], device='cuda:0')


Tensor Math

Task 1.1.6:  Addition

In [7]:
#Assign the results to summed_tensor_operator and summed_tensor_method (+ or add())

summed_tensor_operator = left_tensor + right_tensor
summed_tensor_method = left_tensor.add(right_tensor)

print(summed_tensor_operator)
print()

print(summed_tensor_method)

tensor([[ 8., 10., 12.],
        [14., 16., 18.]], device='cuda:0')

tensor([[ 8., 10., 12.],
        [14., 16., 18.]], device='cuda:0')


Task 1.1.7: Multiplication

In [19]:
# element-wise multiplication, where the corresponding values of two tensors are multiplied together.
# In PyTorch, we can do this using the * operator or the .mul() method
# To multiply number of rows of each must be equal
# [[2, 5], [7, 3], [3]] and [[8], [9], [2], [5]]

ew_tensor_operator = left_tensor * right_tensor
ew_tensor_method = left_tensor.mul(right_tensor)


print(ew_tensor_operator)
print()

print(ew_tensor_method)

# Note that element-wise multiplication is commutative.
# It doesn't matter in what order we multiply the two tensors.
# The product of left_tensor * right_tensor is the same as the product of right_tensor * left_tensor.
# left_tensor * right_tensor == right_tensor * left_tensor


tensor([[ 7., 16., 27.],
        [40., 55., 72.]], device='cuda:0')

tensor([[ 7., 16., 27.],
        [40., 55., 72.]], device='cuda:0')


In [25]:
# Experimenting
a = torch.Tensor([[2, 5, 1], [7, 3, 2], [4, 5, 3]])
b = torch.Tensor([[8], [9], [5]])

print(a * b)

tensor([[16., 40.,  8.],
        [63., 27., 18.],
        [20., 25., 15.]])


Matrix multiplication

Matrix multiplication, which combines the rows and columns of two tensors to generate a new one. We can use the @ operator or the .matmul() method.

In [9]:
# Lets create two new matrices

new_left_tensor = torch.Tensor([[2, 5], [7, 3]])
new_right_tensor = torch.Tensor([[8], [9]])

print(new_left_tensor)
print()
print(new_right_tensor)

tensor([[2., 5.],
        [7., 3.]])

tensor([[8.],
        [9.]])


Task 1.1.8

In [10]:
mm_tensor_operator = new_left_tensor @ new_right_tensor
mm_tensor_method = new_left_tensor.matmul(new_right_tensor)

print(mm_tensor_operator)
print()
print(mm_tensor_method)

# Matrix multiplication is not commutative.
# The number of columns in the tensor on the left must equal
# the number of rows in the tensor on the right.
# If these two dimensions don't match, your code will throw a RunTimeError.

tensor([[61.],
        [83.]])

tensor([[61.],
        [83.]])


Task 1.1.9: Calculate the mean

In [27]:
my_tensor_mean = my_tensor.mean()

print("my_tensor_mean class:", type(my_tensor_mean))
print("my_tensor_mean shape:", my_tensor_mean.shape)
print("my_tensor_mean data type:", my_tensor_mean.dtype)
print("my_tensor_mean device:", my_tensor_mean.device)
print()
print("my_tensor mean:", my_tensor_mean)

my_tensor_mean class: <class 'torch.Tensor'>
my_tensor_mean shape: torch.Size([])
my_tensor_mean data type: torch.float32
my_tensor_mean device: cuda:0

my_tensor mean: tensor(6.5000, device='cuda:0')


Task 1.1.10: Calculate the mean for each column in my_tensor.

In [30]:
my_tensor_column_means = my_tensor.mean(dim=0)
my_tensor_row_means = my_tensor.mean(dim=1)

print("my_tensor:", my_tensor)
print("my_tensor column means:", my_tensor_column_means)
print("my_tensor row means:", my_tensor_row_means)

my_tensor: tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], device='cuda:0')
my_tensor column means: tensor([5.5000, 6.5000, 7.5000], device='cuda:0')
my_tensor row means: tensor([ 2.,  5.,  8., 11.], device='cuda:0')


# Explore Files

Task 1.1.11

Following the pattern of data_dir, assign the path to the multi-class training data to train_dir